name: sms_example
description: Demonstrates how to use the sms plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  sms_plugin:
    path: ../

flutter:
  uses-material-design: true
